version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    hostname: zookeeper-learn
    container_name: zookeeper-learn
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:6.2.0
    hostname: kafka-learn
    container_name: kafka-learn
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
# services:
#   zookeeper:
#     image: wurstmeister/zookeeper:latest
#     ports:
#       - "2181:2181"
#   kafka:
#     image: wurstmeister/kafka:2.11-1.1.1
#     ports:
#       - "9092:9092"
#     links:
#       - zookeeper
#     environment:
#       KAFKA_ADVERTISED_HOST_NAME: ${HOST_IP}
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#       KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
#       KAFKA_DELETE_TOPIC_ENABLE: 'true'
#       KAFKA_CREATE_TOPICS: "topic-test:1:1"
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock